### ISSUE TITLE
Cannot install this plugin with Docker

### ISSUE THREAD

**Issue by tohch4** [burtlo/inspec-resource-pack#1]
Hello, I am trying to build an extension for tohch4/inspec-github-repo#1 [with this `Dockerfile`](https://github.com/tohch4/inspec-github-repo/commit/92790bed00ffa51c2fb44a2d6c252f21ac1425da), and I get errors no matter what I try installing this plugin in the official Dockerized version of inspec from Chef. Here is the debug logging from the `docker build` command.

```
$ docker build -t inspec:4.22.0 -t inspec:latest .
Sending build context to Docker daemon  86.02kB
Step 1/6 : FROM chef/inspec:4.22.0
 ---> ddb9fdb1665c
Step 2/6 : ARG CHEF_LICENSE=accept
 ---> Running in 863eaa70536b
Removing intermediate container 863eaa70536b
 ---> d23d4659acfb
Step 3/6 : ARG INSPEC_LOGLEVEL=debug
 ---> Running in 596561bb5e91
Removing intermediate container 596561bb5e91
 ---> cd09e5c4a819
Step 4/6 : ARG INSPEC_PLUGIN=inspec-resource-pack
 ---> Running in 81f3a4fe06a4
Removing intermediate container 81f3a4fe06a4
 ---> 4061a6c0a16c
Step 5/6 : RUN inspec plugin install     --chef-license=${CHEF_LICENSE}     --log-level=${INSPEC_LOGLEVEL}     ${INSPEC_PLUGIN}}
 ---> Running in 2b073f3f39d3
+---------------------------------------------+
✔ 1 product license accepted.
+---------------------------------------------+
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-supermarket': an existing plugin with that name was loaded via bundle-loading from /usr/local/bundle/gems/inspec-core-4.22.0/lib/bundles/inspec-supermarket.rb
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-habitat': an existing plugin with that name was loaded via core-loading from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-habitat/lib/inspec-habitat.rb
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-reporter-json-min': an existing plugin with that name was loaded via core-loading from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-reporter-json-min/lib/inspec-reporter-json-min.rb
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-artifact': an existing plugin with that name was loaded via core-loading from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-artifact/lib/inspec-artifact.rb
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-plugin-manager-cli': an existing plugin with that name was loaded via core-loading from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli.rb
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-reporter-html2': an existing plugin with that name was loaded via core-loading from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-reporter-html2/lib/inspec-reporter-html2.rb
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-compliance': an existing plugin with that name was loaded via core-loading from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-compliance/lib/inspec-compliance.rb
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-init': an existing plugin with that name was loaded via core-loading from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-init/lib/inspec-init.rb
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-habitat': an existing plugin with that name was loaded via system_gem-loading from train-habitat
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-aws': an existing plugin with that name was loaded via system_gem-loading from train-aws
[2020-09-25T05:16:57+00:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-winrm': an existing plugin with that name was loaded via system_gem-loading from train-winrm
/usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/plugin/v2/installer.rb:329:in `rescue in install_gem_to_plugins_dir': Unable to resolve dependency: user requested 'inspec-resource-pack} (> 0)' (Inspec::Plugin::V2::InstallError)
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/plugin/v2/installer.rb:323:in `install_gem_to_plugins_dir'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/plugin/v2/installer.rb:303:in `install_from_remote_gems'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/plugin/v2/installer.rb:72:in `install'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:412:in `install_attempt_install'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:364:in `install_from_remote_gem'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:123:in `install'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/base_cli.rb:35:in `start'
        from /usr/local/bundle/gems/inspec-bin-4.22.0/bin/inspec:11:in `<top (required)>'
        from /usr/local/bundle/bin/inspec:23:in `load'
        from /usr/local/bundle/bin/inspec:23:in `<main>'
/usr/local/lib/ruby/2.7.0/rubygems/resolver.rb:235:in `search_for': Unable to resolve dependency: user requested 'inspec-resource-pack} (> 0)' (Gem::UnsatisfiableDependencyError)
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver.rb:285:in `block in sort_dependencies'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver.rb:279:in `each'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver.rb:279:in `sort_by'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver.rb:279:in `with_index'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver.rb:279:in `sort_dependencies'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
        from /usr/local/lib/ruby/2.7.0/rubygems/resolver.rb:192:in `resolve'
        from /usr/local/lib/ruby/2.7.0/rubygems/request_set.rb:423:in `resolve'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/plugin/v2/installer.rb:324:in `install_gem_to_plugins_dir'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/plugin/v2/installer.rb:303:in `install_from_remote_gems'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/plugin/v2/installer.rb:72:in `install'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:412:in `install_attempt_install'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:364:in `install_from_remote_gem'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:123:in `install'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/base_cli.rb:35:in `start'
        from /usr/local/bundle/gems/inspec-bin-4.22.0/bin/inspec:11:in `<top (required)>'
        from /usr/local/bundle/bin/inspec:23:in `load'
        from /usr/local/bundle/bin/inspec:23:in `<main>'
The command '/bin/sh -c inspec plugin install     --chef-license=${CHEF_LICENSE}     --log-level=${INSPEC_LOGLEVEL}     ${INSPEC_PLUGIN}}' returned a non-zero code: 1
```

**Comment by tohch4** [comment]
I got a little farther, I did `rvm install ruby-2.7.1 &&  rvm use ruby-2.7.1 && gem install inspec && inspec plugin install --log-level=debug  inspec-resource-pack inspec` yielded Gem collisions errors. But this is a newer local version installed outside of Docker.

```
$  docker run -it chef/inspec:latest version --chef-license=accept
4.21.3
```

I will dig into this a little more.
